### ISSUE TITLE
WIKI page mostly written

### ISSUE THREAD

**Issue by yoonsuk27** [SionLee22200538/OSSL_2023TeamProject#9]

**Comment by yoonsuk27** [comment]
Still wiki의 서비스 목록의 "사용가이드" need to be written

**Comment by yoonsuk27** [comment]
협업 목록 "개발일지" Week 1,2 written 
Week 3 need to be finished

**Comment by yoonsuk27** [comment]
We have to write about 

Especially for
current() and draw() functions

**Comment by SionLee21** [comment]
오타 수정, 내용 검수 및 수정

**Comment by SionLee21** [comment]
finished
